-- sp_columns RAT01800



/* Table */
BEGIN TRAN
IF (OBJECT_ID('dbo.RAT00200') IS NOT NULL)
   GRANT REFERENCES, SELECT, INSERT, DELETE, UPDATE ON [dbo].[RAT00200] TO [RXO00100]
GO
-- COMMIT

/* View */
BEGIN TRAN
IF (OBJECT_ID('dbo.RAV07600') IS NOT NULL)
   GRANT SELECT ON [dbo].[RAV07600] TO [RXO00100]
GO
-- COMMIT


/* Procedure */
BEGIN TRAN
IF COL_LENGTH('dbo.RAT01800', 'datalimitepausa') IS NULL 
BEGIN
   ALTER TABLE [dbo].[RAT01800] ADD [datalimitepausa] DATETIME
END
-- COMMIT


BEGIN TRAN
IF (OBJECT_ID('dbo.RAD02500') IS NOT NULL)
   GRANT EXECUTE ON [dbo].[RAD02500] TO [RXO00100]
GO
-- COMMIT